---
format_version: '13'
default_step_lib_source: https://github.com/bitrise-io/bitrise-steplib.git
meta:
  bitrise.io:
    stack: osx-xcode-15.1.x
    machine_type_id: g2-m1.4core
app:
  envs:
  - ACCESS_KEY: '120'
  - GITHUB_TOKEN: GITHUB_TOKEN
    opts:
      is_expand: false
  - SLACK_WEBHOOK: https://tempuri.org
pipelines:
  p1:
    workflows:
      tmp: {}
workflows:
  custom-steplib-steps:
    steps:
    - https://github.com/zoltanszabo-bitrise/custom-steplib.git::xcode-test:
        title: Custom GitHub (user) steplib
    - https://github.com/zoltan-szabo-bitrise/custom-steplib.git::xcode-test:
        title: Custom GitHub (org) steplib
    - https://gitlab.com/zoltanszabo-bitrise/custom-steplib.git::xcode-test:
        title: Custom GitLab (user) steplib
    - https://gitlab.com/steplib/custom-steplib.git::xcode-test:
        title: Custom GitLab (group) steplib
    - https://bitbucket.org/zoltan-szabo-bitrise/custom-steplib.git::xcode-test:
        title: Custom BitBucket steplib
  git-steps:
    steps:
    - git::https://github.com/bitrise-io/steps-fastlane.git@master:
        title: GitHub (org) (https) step
        inputs:
        - lane: github1
    - git::git@github.com:bitrise-io/steps-fastlane.git@master:
        title: GitHub (org) (ssh) step
        inputs:
        - lane: github2
    - git::https://github.com/zoltanszabo-bitrise/steps-fastlane.git@master:
        title: GitHub (user) (https) step
        inputs:
        - lane: github3
    - git::git@github.com:zoltanszabo-bitrise/steps-fastlane.git@master:
        title: GitHub (user) (ssh) step
        inputs:
        - lane: github4
    - git::https://gitlab.com/steplib/steps-fastlane.git@master:
        title: GitLab (org) (https) step
        inputs:
        - lane: gitlab1
    - git::git@gitlab.com:steplib/steps-fastlane.git@master:
        title: GitLab (org) (ssh) step
        inputs:
        - lane: gitlab2
    - git::https://gitlab.com/zoltanszabo-bitrise/steps-fastlane.git@master:
        title: GitLab (user) (https) step
        inputs:
        - lane: gitlab3
    - git::git@gitlab.com:zoltanszabo-bitrise/steps-fastlane.git@master:
        title: GitLab (user) (ssh) step
        inputs:
        - lane: gitlab4
    - git::https://bitbucket.org/zoltan-szabo-bitrise/steps-fastlane.git@master:
        title: Bitbucket (https) step
        inputs:
        - lane: bitbucket1
    - git::git@bitbucket.org:zoltan-szabo-bitrise/steps-fastlane.git@master:
        title: Bitbucket (ssh) step
        inputs:
        - lane: bitbucket2
  local-steps:
    steps:
    - path::./spec/integration/fixture/test_local_step: {}
    - path::./spec/integration/fixture/test_local_step:
        title: A local step with overwritten title & input
        inputs:
        - company_name: Mando
    - path::./local/step:
        title: Local step (relative - ./...)
    - path::~/develop/go/src/github.com/bitrise-io/steps-timestamp:
        title: Local step (absolute - ~/...)
    - path::$HOME/develop/go/src/github.com/bitrise-io/steps-timestamp:
        title: Local step (absolute - $HOME/...)
  steplib-steps:
    steps:
    - https://github.com/bitrise-io/bitrise-steplib.git::script@0.9.0:
        title: Full explicit ID (library::id@version)
        inputs:
        - content: |-
            #!/usr/bin/env bash
            echo "Hello World!"
    - "::script@0.9.0":
        title: Implicit library, explicit version (::id@version)
        inputs:
        - content: |-
            #!/usr/bin/env bash
            echo "Hello World!"
    - script@0.9.0:
        title: Implicit library, explicit version (id@version)
        inputs:
        - content: |-
            #!/usr/bin/env bash
            echo "Hello World!"
    - "::script@":
        title: Implicit library, implicit version (::id@)
        inputs:
        - content: |-
            #!/usr/bin/env bash
            echo "Hello World!"
    - script@:
        title: Implicit library, implicit version (id@)
        inputs:
        - content: |-
            #!/usr/bin/env bash
            echo "Hello World!"
    - script:
        title: Full implicit ID (id)
        inputs:
        - content: |-
            #!/usr/bin/env bash
            echo "Hello World!"
    envs:
    - A: B
      opts:
        is_expand: false
  tmp:
    envs:
    - FOO: BAZ
    steps:
    - script@1:
        inputs:
        - content: |-
            #!/usr/bin/env bash
            echo "Hello World!"
        title: My script
trigger_map:
- push_branch: tmp
  type: push
  workflow: tmp
